[package]
name = "win_ui"
version = "0.1.0"
authors = ["joe"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.22"
raw-window-handle = "0.3"
#winrt = "0.7"
winrt = { git = "https://github.com/microsoft/winrt-rs" }
bindings = { path = "./bindings"}
rand = "0.7"

[build-dependencies]
embed-resource = "1.3"

[package.metadata.winrt.dependencies]
"Microsoft.UI.Xaml" = "2.5.0-prerelease.200609001"
"Microsoft.VCRTForwarders.140" = "1.0.6"